@startuml
class SessionService {
    - <<readonly>> _logger : ILogger
    - <<readonly>> _userManager : IUserManager
    - _currentUser : User?
    + CurrentUser : User? <<get>>
    + StartSession(username:string, password:string) : void
    + EndSession() : void
}
@enduml
