@startuml
class UserManager {
    - <<readonly>> _logger : ILogger
    - <<readonly>> _usersFilePath : string
    + Users : List<User> <<get>>
    - LoadUsers() : void
    - SaveUsers() : void
    + CreateUser(name:string, username:string, password:string) : void
    + Initialize() : void
    + Shutdown() : void
    + RemoveUserByUsername(username:string) : bool
    + AuthenticateUser(username:string, password:string) : User?
    + GetUserByUsername(username:string) : User?
    + UserManager(logger:ILogger)
}
IUserManager <|-- UserManager
@enduml
