@startuml
interface IOrderQueue {
    ActiveOrders : List<Order> <<get>>
    ArchivedOrders : List<OrderArchiveSnapshot> <<get>>
    Initialize() : void
    Shutdown() : void
    PlaceOrder(username:string, pizzas:List<IPizza>) : int
    CancelOrder(orderId:int, employee:bool, username:string) : void
    CancelAllOrders() : void
    ClearOrderHistory() : void
    GetOrder(orderId:int) : Order
    GetAllOrders() : List<Order>
    SetOrderStatus(orderId:int, status:OrderStatus) : void
    AdvanceOrderStatus(orderId:int) : void
    GetActiveOrdersByStatus(status:OrderStatus) : List<Order>
    GetActiveOrdersByUserId(username:string) : List<Order>
    GetArchivedOrdersByUserId(username:string) : List<OrderArchiveSnapshot>
}
@enduml
