@startuml
interface IPromotionManager {
    Promotions : List<IPromotion> <<get>>
    GetActivePromotions() : IEnumerable<IPromotion>
    GetBestPromotion(order:Order) : (string? Name, decimal Discount)
}
@enduml
