@startuml
interface IPromotion {
    + Id : Guid <<get>>
    Name : string <<get>>
    StartDate : DateTime <<get>>
    EndDate : DateTime <<get>>
    IsActive() : bool
    IsApplicable(order:Order) : bool
    CalculateDiscount(order:Order) : decimal
}
@enduml
