@startuml
class EmployeePanel <<partial>> {
    - <<readonly>> _orderQueue : IOrderQueue
    - <<readonly>> _menu : Menu
    - <<readonly>> _logger : ILogger
    + EmployeePanel(orderQueue:IOrderQueue, menu:Menu, logger:ILogger)
    - ViewOrders() : void
    - UpdateOrderStatus() : void
    - CancelOrder() : void
    - ManageOrders() : void
    + Show() : void
}
@enduml
