@startuml
class ListOrders {
    - <<readonly>> _orderQueue : IOrderQueue
    + ListOrders(orderQueue:IOrderQueue)
    + ShowAllActiveOrders() : void
    + ShowAllArchivedOrders() : void
    + ShowUserActiveOrders(username:string) : void
    + ShowUserArchivedOrders(username:string) : void
    - PrintOrder(order:Order) : void
    - PrintArchivedOrder(order:OrderArchiveSnapshot) : void
}
@enduml
