@startuml
class LoginPanel {
    - <<readonly>> _logger : ILogger
    - <<readonly>> _userManager : IUserManager
    - <<readonly>> _sessionService : SessionService
    - LoggedIn : bool = false
    + LoginPanel(logger:ILogger, userManager:IUserManager, sessionService:SessionService)
    - Login() : void
    - Register() : void
    + Show() : void
}
@enduml
