@startuml
class Menu {
    + <<required>> MenuItems : List<MenuItem> <<get>> <<init>>
    + <<required>> Ingredients : List<Ingredient> <<get>> <<init>>
}
class MenuItem {
    + Id : Guid <<get>> <<init>>
    + <<required>> Name : string <<get>> <<init>>
    + <<required>> Price : decimal <<get>> <<init>>
    + Ingredients : List<Ingredient> <<get>> <<init>>
}
class Ingredient {
    + Id : Guid <<get>> <<init>>
    + <<required>> Name : string <<get>> <<init>>
    + <<required>> Price : decimal <<get>> <<init>>
    + <<required>> Restriction : IngredientRestriction <<get>> <<init>>
    + Type : IngredientType <<get>> <<init>>
}
@enduml
